### PR TITLE
fix: ensure RSA key length fullfills 4096bit requirement (#2905)

### LINKED ISSUE #2905: Ensure PKCS RSA key length fullfills 4096bit requirement
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

See https://github.com/ory/hydra/pull/2625#discussion_r775475763

### Reproducing the bug

See above

### Relevant log output

_No response_

### Relevant configuration

_No response_

### Version

master

### On which operating system are you observing this issue?

_No response_

### In which environment are you deploying?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by aarmam**
Fixes #2905

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](https://github.com/ory/docs).

### CODE REVIEW

File: hsm/manager_hsm_test.go [hunk 1]
```diff
@@ -62,78 +62,96 @@ func TestKeyManager_HsmKeySetPrefix(t *testing.T) {
...
 	hsmContext := NewMockContext(ctrl)
 	defer ctrl.Finish()
+	l := logrusx.New("", "")
+	c := config.MustNew(context.Background(), l, configx.SkipValidation())
+	keySetPrefix := "application_specific_prefix."
+	c.MustSet(context.Background(), config.HSMKeySetPrefix, keySetPrefix)
+	m := hsm.NewKeyManager(hsmContext, context.TODO(), c)
 
-	rsaKey, err := rsa.GenerateKey(rand.Reader, 512)
+	rsaKey3072, err := rsa.GenerateKey(rand.Reader, 3072)
```
Comment (alnr) [inline hsm/manager_hsm_test.go:71]:
```suggestion
	rsaKey3072, err := rsa.GenerateKey(rand.Reader, 3072)
	require.NoError(t, err)
```

File: hsm/manager_hsm.go [hunk 2]
```diff
@@ -51,10 +52,11 @@ var ErrPreGeneratedKeys = &fosite.RFC6749Error{
 	DescriptionField: "Cannot add/update pre generated keys on Hardware Security Module",
 }
 
-func NewKeyManager(hsm Context, config *config.DefaultProvider) *KeyManager {
+func NewKeyManager(hsm Context, ctx context.Context, config *config.DefaultProvider) *KeyManager {
 	return &KeyManager{
-		Context:      hsm,
-		KeySetPrefix: config.HSMKeySetPrefix(),
+		Context: hsm,
+		ctx:     ctx,
```
Comment (alnr) [inline hsm/manager_hsm.go:58]: I suggest not storing the context in the KeyManager. I'd suggest passing the configuration options (`KeySetPrefix` and `DevMode` for example) to the constructor instead and storing them directly.

**Review by alnr — CHANGES_REQUESTED** [review]
Cool! Sorry, not familiar with the spec. Is the min key size defined there as 4096 bits?

File: hsm/manager_hsm.go (hunk 2 above)
Comment (aarmam) [reply hsm/manager_hsm.go:58]: I might remember it wrong, but one of my previous code review, the suggestion was to pass configuration context so when configuration is updated, the changes will be used. Also because I am not full time go developer I code by [example quite often](https://github.com/ory/hydra/blob/v2.0.3/persistence/sql/persister.go#L106). That said I am happy to make the change - just clearifing how I got here! :)

**Comment by aarmam** [comment]
> Cool! Sorry, not familiar with the spec. Is the min key size defined there as 4096 bits?

This constraint came from [here](https://github.com/ory/hydra/blob/v2.0.3/jwk/generate.go#L21)

**Comment by alnr** [comment]
@aarmam Would you mind rebasing your PR onto master? We've improved our tooling so the copyright header won't require updating every year. Thanks so much!

Pinging @aeneasr for review, too.

File: hsm/manager_hsm.go (hunk 2 above)
Comment (aeneasr) [reply hsm/manager_hsm.go:58]: Hey, sorry for the late review. @alnr is correct here, the context should come from the function caller, not the service itself. I checked quickly and `getKeySetAttributes` is being called from two functions, both of which have context.Context available. I'll push the changes shortly

**Review by aeneasr — APPROVED** [review]
