### PR TITLE
Replace fatal error of jaeger initialization with print

### LINKED ISSUE #2642: Jaeger being unavailable is a fatal error that stops service from starting
**Describe the bug**

A failure to initialize the tracer is fatal, even though it won't affect the functionality of the service.

https://github.com/ory/hydra/blob/f588ec69d4fa03f602d3cbb20abd4188195a7375/driver/registry_base.go#L436

### PR DESCRIPTION
**Pull request by Gituser143**
Replace `Fatalf()` with `Println()` to log when unable to initialize a tracer. This avoid unnecessary exits. ~~Additionally, total 3 attempts are made to init the tracer.~~

Fixes #2642 

CC: @aeneasr 

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.

### CODE REVIEW

**Comment by Gituser143** [comment]
Hi @aeneasr, I'm not sure why the CI test failed, could you tell me what I'm missing? I wasn't able to make sense of the logs either, the below step failed due to several connections being refused.
```
.bin/go-acc -o coverage.out ./... -- -failfast -timeout=20m -tags sqlite
```

File: driver/registry_base.go [hunk 1]
```diff
@@ -432,11 +432,20 @@ func (m *RegistryBase) SubjectIdentifierAlgorithm() map[string]consent.SubjectId
...
 func (m *RegistryBase) Tracer(ctx context.Context) *tracing.Tracer {
 	if m.trc == nil {
-		t, err := tracing.New(m.l, m.C.Tracing())
-		if err != nil {
-			m.Logger().WithError(err).Fatalf("Unable to initialize Tracer.")
+		var err error
+		var t *tracing.Tracer
+
+		// Make 3 attempts to initialize tracer
+		for i := 0; i < 3; i++ {
```
Comment (aeneasr) [inline driver/registry_base.go:439]: Good idea! Unfortunately, this doesn't wait so it will try 3 times in rapid succession and failing. I think it's ok to just print the error with `Error` to the logger without retries!

**Review by aeneasr — CHANGES_REQUESTED** [review]

**Comment by aeneasr** [comment]
Ah yeah, that's just a flaky test :/

File: driver/registry_base.go (hunk 1 above)
Comment (Gituser143) [reply driver/registry_base.go:439]: I was meaning to put a `time.Sleep()` at the end of each iteration, but was unsure of how long it should sleep. Would you suggest I do that or do I get rid of the retries entirely?

**Comment by Gituser143** [comment]
@aeneasr I've removed the retries and just logged the error as of now. Do let me know if I should revert to the 3 attempts + sleep approach.

File: driver/registry_base.go [hunk 2]
```diff
@@ -434,9 +434,10 @@ func (m *RegistryBase) Tracer(ctx context.Context) *tracing.Tracer {
 	if m.trc == nil {
 		t, err := tracing.New(m.l, m.C.Tracing())
 		if err != nil {
-			m.Logger().WithError(err).Fatalf("Unable to initialize Tracer.")
+			m.Logger().WithError(err).Println("Unable to initialize Tracer.")
```
Comment (aeneasr) [inline driver/registry_base.go:437]:
```suggestion
			m.Logger().WithError(err).Error("Unable to initialize Tracer.")
```

**Review by aeneasr — CHANGES_REQUESTED** [review]
Awesome, thank you for your contribution! This looks pretty good and I have some ideas how to improve it further :)

File: driver/registry_base.go (hunk 2 above)
Comment (Gituser143) [reply driver/registry_base.go]: Done!

**Comment by Gituser143** [comment]
@aeneasr is there anything else I can add to this PR?

**Comment by aeneasr** [comment]
Just waiting for CI to pass :) It's flaky atm but I am restarting the job now

**Comment by Gituser143** [comment]
Hey @aeneasr, is there anything I have to change to pass the code coverage CI?
